CREATE TABLE PC_CONDITION (
	PC_COND_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    PC_COND_CHAR_HEALTH_ID INT UNSIGNED NOT NULL,
    PC_COND_CHAR_MANA_ID INT UNSIGNED NOT NULL,
    PC_COND_CHAR_LEVEL_ID INT UNSIGNED NOT NULL,
	PRIMARY KEY ( PC_COND_ID )
);