DROP TABLE IF EXISTS PLAYER_CHARACTER;

DROP TABLE IF EXISTS PC_SETTINGS;

DROP TABLE IF EXISTS CHARACTER_CLASS;

DROP TABLE IF EXISTS BASE_SKILLSET;

DROP TABLE IF EXISTS SKILLSET_MARTIALISM;

DROP TABLE IF EXISTS PC_CONDITION;

DROP TABLE IF EXISTS CHAR_LEVEL;

DROP TABLE IF EXISTS CHAR_HEALTH;

DROP TABLE IF EXISTS CHAR_MANA;

DROP TABLE IF EXISTS GAME_MAP;

DROP TABLE IF EXISTS BASE_ROOM;

DROP TABLE IF EXISTS BASE_ROOM_EXIT;
